[tool.black]
line-length = 100
target-version = ["py311", "py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "I", "W", "UP", "B"]
ignore = []
exclude = [
  ".venv",
  "build",
  "dist",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
filterwarnings = [
  'ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning',
]
